### ISSUE TITLE
Ask for how to set 'mild' and 'chaotic'

### ISSUE THREAD

**Issue by FrankSinatral** [wuxiyang1996/Heterogeneous_Highway_Env#1]
Thanks for your great contributions! But I wonder if you can provide with more details in your readme file on how to change your configurations for the heterogeneous highway env such as which one is 'Mild' and which one is 'Chaotic' described in your paper.

**Comment by wuxiyang1996** [comment]
Hi, the Mild environment is HighwayEnvHetero (id='highway-hetero-v0') at https://github.com/wuxiyang1996/Heterogeneous_Highway_Env/blob/b96a34754f608bf3e2e9832a35c828bf11782794/envs/highway_env.py#L183 

and the Chaotic one is HighwayEnvHetero_H (id='highway-hetero-H-v0') at 
https://github.com/wuxiyang1996/Heterogeneous_Highway_Env/blob/b96a34754f608bf3e2e9832a35c828bf11782794/envs/highway_env.py#L395

**Comment by FrankSinatral** [comment]
Thanks!
