### ISSUE TITLE
How to fix the initial scene

### ISSUE THREAD

**Issue by Captain6606** [wuxiyang1996/Heterogeneous_Highway_Env#3]
I have trained the iPLAN model and set checkpoint_paths to the address of the model. When I set global_seed to a fixed value, I still get a different reward each time in the Highway_Env_easy scenario.I think the scenario of Heterogeneous_Highway_Env is different each time it is initialized, so I would like to ask you how to fix the initial position and speed size of 5 agents and 50 vehicles.In a word，I want to know if running the same conditions twice will result in the same result.Thank you very much for your reply.

**Comment by wuxiyang1996** [comment]
Did not try to fix the initial scene before.

After looking into the code, I suggest to start by fixing the random seed ID here: https://github.com/wuxiyang1996/Heterogeneous_Highway_Env/blob/b96a34754f608bf3e2e9832a35c828bf11782794/envs/common/abstract.py#L46
with the random seed ID defined in the config file.

**Comment by Captain6606** [comment]
Thank you for your reply.
    I've tried the approach you mentioned, but it doesn't seem to work very well.So I would like to ask you if there is a way to fix the generated vehicle position and speed each time and observe the reward each time.Determine if the model is deterministic.Again, I look forward to hearing from you.

**Comment by wuxiyang1996** [comment]
I checked the code again, you need to remove the self.seed() as well.
https://github.com/wuxiyang1996/Heterogeneous_Highway_Env/blob/b96a34754f608bf3e2e9832a35c828bf11782794/envs/common/abstract.py#L47

Everything relates to randomness (behavior, initial position, etc) should only relate to this hyperparameter.

**Comment by Captain6606** [comment]
I solved the problem，Thank you for your suggestion.
